---
title: "大学生垃圾分类回收行为影响因素"
author: "XXX"
date: "2019年11月05日"
fontsize: 10pt
output: 
  beamer_presentation: 
    latex_engine: xelatex
    template: beamer_default.tex
    theme: cambridgeUS
    colortheme: whale
    fonttheme: professionalfonts
    highlight: pygments
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 引言
垃圾分类回收是对垃圾收集处置传统方式的改革， 是对
垃圾进行有效处置的一种科学管理方法（曲英，2009）。 人们面
对日益增长的垃圾产量和环境状况恶化的局面， 如何通过垃
圾分类管理， 最大限度地实现垃圾资源利用， 减少垃圾处置
量，改善生存环境质量，是当前世界各国共同关注的迫切问题
之一（黄小洋，2012）。\par

大学生既是生活垃圾的制造者，也是生活垃圾分类回收的推动者，且其作为这个社会中思想最活跃可塑性最强的一个群体,且处于各种习惯的形成阶段，因此，研究大学生垃圾来及分类的意愿和回收行为的相关问题，对电子垃圾回收工作在全社会展开和建设资源节约型社会有着及其重要的时间价值。

# 文献回顾
## 理论层面
Mannetti，Pierro，＆ Livi 认为，主要有两个与个体
动机相关的理论框架可用来解释人们参与回收的
行为。  

1. 由于个体都是追求其效
用最大化的，所以他们会根据物质刺激的大小来不
断调整自己的行为。

2. 个
体的内在价值观、信仰和态度等是其行为的主要激
励因素。\newline

现在，越来越多的研究将以上两
个框架结合起来，从更加全面的角度研究人们从事
回收行为的影响因素，比如 Valle 等人的研究、Michiyo 的研究、Saphores 等人的研究等等。\par

---

一般环境态度是研究最多的消费者回收
行为的预测变量。但是，现有文献对于两者之间的关系并没有给出一致的研究结果。

- Tonglet 及其合作者在研究中发
现，亲回收态度是回收行为的一个主要预测变
量。
- Corral-Verdugo，Werner ＆ Makela，McCarty ＆ Shrum等分别在各自的研究中证实了
特定环境态度对于回收行为的影响。

还有少部分
研究探索了过去的回收行为经验和回收行为两者
之间的关系。

- Michiyo 的研究发现，消费者过去的
回收经验对于回收行为的预测比态度变量对于回
收行为的预测更加有效。
- Tonglet 等人也发现，
过去的回收经验是回收行为的一个重要预测变
量。

---

而另外一些学者从经济性角度考虑，认为回
收的便利性会对回收行为产生重大影响。所研
究的相关变量包括回收箱的距离、路边回收设施
的提供、储存空间的大小等。同时，许多研究
调查了人口统计学变量、社会经济学变量与回收行
为之间的关系。调查最多的人口统计学和社会经济
学变量包括年龄、受教育程度、性别、收入、居住类
型、种族、家庭大小、政治联系等。此外，现
有文献中所研究的回收行为的影响因素还有环境知
识、社会规范、个体规范、控制点等变量。

而以上文献研究的
核心内容都可以整合到 Hwang，Kim ＆ Jeng 所提
出的“关于环境行为的理论框架”模型中。在该模
型中，Hwang，Kim ＆ Jeng 将影响环境行为的因素
分为三类: 认知因素、情感因素和情境因素。

---

## 垃圾分类现状

- 梁爽等通过问卷调查、访谈等方式，调
查研究了长株潭各高校的垃圾分类现状，并在此基础上
提出了加大宣传教育，增加资金投入，细化分类标识，
鼓励环保类社团参与等垃圾分类回收的改进方法 ；
- 王丹
青等以烟台大学为例，采用问卷调查、实地调研的
方法，对高校生活垃圾源头分类行为进行调查分析，结
果表明，生活垃圾源头分类在高校虽已被普遍认可但在
实际分类中存在“知与行不合一”的现象。

## 垃圾分类意识

- 李雪芹采用问卷调查法，对
江西省几所高校学生垃圾分类回收参与意识进行调查，
结果显示，目前大学生垃圾分类回收意识欠缺，对垃圾
分类回收的知识知之甚少，对垃圾分类回收责任主体认
识错位，未养成垃圾分类回收的习惯 ；

- 尹洁林等学
者以大学生群体为研究对象，讨论大学生电子垃圾回收
行为意向的影响因素以及各种增加电子垃圾回收行为做
法有效性的偏好 ；

---

- 陈绍军和李如春采用二元 logistic
回归模型，对影响城市居民垃圾分类意愿和行为的因素及其差异进行了实证分析，并进一步探讨垃圾分类的内
在机制。从高校垃圾分类管理模式的角度出发 ：

- 张宏艳和王卓然对高校学生生活垃圾资源化可行性进行了
分析，提出了简单可行的高校生活垃圾资源化管理模式；

- 徐文立运用现代网络资源，建立垃圾换积分，积分
换实物的网络回收服务平台，实现垃圾与物品之间的有
效交换，使大学生真切感受到生活垃圾的价值，促进校
园文明健康和安全稳定。\par


# 拟研究的问题
影响大学生群体垃圾分类回收的回收意愿和回收行为的主要决定因素，对当前积极推行的垃圾分类回收有一定的政策借鉴意义。

# 拟采用的方法
## 调查问卷
采用调查问卷的方式收集相关指标对回收意愿和回收行为的各种影响因素进行度量分析\par
缺点：\newline
- 首先，数据结果具有一次性的缺陷，而且变量难以控制 
- 其次，通过问卷调查得到的数据，只能对测试人
员的行为进行静态分析，而人类的行为选择是动态变化
的
- 最后，垃圾分类等资源环境问题是在受到人类各
种行为特征和行为选择的长期作用影响下形成的，一次
简单的问卷调查很难得到测试人员的真实行为信息。

## 实验
该方法可以克服上述缺点，但是，没有条件的话，基本不太可能。

# 拟得出的结论
希望能在各种变量中找出对垃圾回收行为影响最大的因素。

