---
title: "环境经济学文献梳理"
author:
  - 石威展
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
classoption: "hyperref,"
---

# 不知道该取个啥标题
禀赋
效应来源于卖方把商品作为已有财产来对待, 是不打
算 “失去”的, 但在多次交易的商人手里则完全不同,
这给政策实施以新的启示, 即倘若污染权的分配由独
立的职业拍卖方拍卖, 交易会容易实现。当然在市场
机制不是很健全的我国, 职业拍卖更为重要, 它可以
避免不必要的租金损失。\par
行为人衡量收益和成本的贴现率在
不同的时间是不一致的 (Laibson, 2003)。 行为人对那
些在较近的未来有得益的项目有较大的折算率, 而对
那些比较远的得益有较小的折算率, 或者说行为人是
有即时冲动的 (Laibson, 2003)。\par
<font color=Crimson size=5>现状偏好理论” (Kahneman, 1991)</font>是指行为人
更偏向于维持现状而不是改变。在环境经济学中, 它
体现为即使在市场上有一个很有效的技术, 污染者也
倾向于维持现状, 因为高昂的成本会使行为人夸大这
种损失, 这就导致一种次优的结局。

\section[一篇硕士论文（新疆大学）]{关于环境的行为经济学分析——杨干生}
\subsection{关于环境的行为经济学分析}
\subsubsection{经济主体追求环境福利最大化时的有限理性}
#### 参照效应
#### 敏感度降低效应（diminishing sensitivity）
#### 不愿失去效应

\subsection{在经济主体不是追求福利最大化时的行为分析}
\subsubsection{追求公平及遭受不公平时进行报复}
\subsubsection{意识形态的经济意义}
**意识形态的4个假说** \\
> H1：意识形态对特定人群中各围观经济主体目标函数的影响
> H2：对特定人群中各经济利益主题预期效用函数的影响
> H3：意识形态与经济决策主题之间的互动
> H4：环保主义意识形态
  > 共同信仰
  

# 大学生环保行为的经济学实验研究

## 摘要 
运用实验经济学研究方法，基于博弈视角，不仅设计了不同奖惩机制，且
考虑到社会规制和声誉因素的影响，设计了关于高校宿舍垃圾分类行为的经济学实验。最后结合传统调查问卷形
式，探讨个体特征与决策行为的联系。实验方法获得的数据真实可靠，对于高校或政府等公共部门制定环境监管
政策具有重要意义。

## 引言
## 文献综述
国内外大量研究
表明，奖惩措施是影响个体捐献的有效举措之一。实施
\textcolor{red}{奖惩措施}有效地减少了公共物品捐献中的搭便车现象，
提高了捐献水平，维持群体内的合作\par

关于公共物品捐献中搭便车者的行为动机，国内
外学者从生物学、经济学、社会学和心理学等不同学科
视角展开研究。从个体特征的角度出发 ：Chaudhuri & 
Sbai[
11]
使用随机匹配的方式进行重复实验，研究发现在
信任水平上不同性别并没有强烈差异，但与男性相比女性互惠水平更低 ；周业安等[
12]发现，不同性别的个
体表现出有差异的社会偏好，并影响公共物品的自愿供
给水平 ；Sutter 等[
13]以儿童和青少年为研究对象设计激
励实验，发现性格暴躁的儿童和青少年更容易用钱购买
烟酒，储蓄倾向相对较低。从社会偏好的角度出发 ：刘
文忻等发现，个人社会偏好异质性对实验中的合作行为
有显著影响，而影响公共物品提供的主要外在因素是信
息交流和私人收益率 ；Carlsson 等[
14]研究了在修建桥梁
事件中，社会因素对个体捐款行为意愿的影响，结果表
明社会偏好信息的公开对捐款行为具有促进作用，例如，
如果个体捐款为零，平均捐款额会降低 20%。从社会声
誉因素的角度出发 ：Markowitz & Shariff[
15]发现社会的
交互行为，包括自豪感、羞耻感等，可能会促进个体的
环保行为 ；Ashraf 等[
16]研究了在公共组织中非物质奖
励如何影响个体工作行为 ；Kosfeld & Neckermann[
17]，
Bradler 等[
18]在公司里进行了田野实验，分析了非物质
奖励（即积极的社会认知与社会声誉）如何影响员工的工
作情况 ；Bénabou & Tirole[
19]研究发现很多人为了提高
自己的形象和声誉愿意采取有利于社会的行为，通过自
己的行为希望自身得到社会的认可。 \par

在研究高校宿舍垃圾分类行为中，很多学者也从不
同的角度进行了多方面的研究。从高校垃圾分类现状的
角度出发 ：梁爽等[
20]通过问卷调查、访谈等方式，调
查研究了长株潭各高校的垃圾分类现状，并在此基础上
提出了加大宣传教育，增加资金投入，细化分类标识，
鼓励环保类社团参与等垃圾分类回收的改进方法 ；王丹
青等[
21]以烟台大学为例，采用问卷调查、实地调研的
方法，对高校生活垃圾源头分类行为进行调查分析，结
果表明，生活垃圾源头分类在高校虽已被普遍认可但在
实际分类中存在“知与行不合一”的现象。从高校学生垃
圾分类意识的角度出发 ：李雪芹[
4]采用问卷调查法，对
江西省几所高校学生垃圾分类回收参与意识进行调查，
结果显示，目前大学生垃圾分类回收意识欠缺，对垃圾
分类回收的知识知之甚少，对垃圾分类回收责任主体认
识错位，未养成垃圾分类回收的习惯 ；尹洁林等[
22]学
者以大学生群体为研究对象，讨论大学生电子垃圾回收
行为意向的影响因素以及各种增加电子垃圾回收行为做
法有效性的偏好 ；陈绍军和李如春[
23]采用二元 logistic
回归模型，对影响城市居民垃圾分类意愿和行为的因素及其差异进行了实证分析，并进一步探讨垃圾分类的内
在机制。从高校垃圾分类管理模式的角度出发 ：张宏艳
和王卓然[
24]对高校学生生活垃圾资源化可行性进行了
分析，提出了简单可行的高校生活垃圾资源化管理模式；徐文立[
25]运用现代网络资源，建立垃圾换积分，积分
换实物的网络回收服务平台，实现垃圾与物品之间的有
效交换，使大学生真切感受到生活垃圾的价值，促进校
园文明健康和安全稳定。\par

\zihao{4}\textcolor{red}{现有文献中获得数据的方法基本上都是问卷调查}
等传统形式。\normalsize \textcolor{blue}{其缺陷}:

> 首先，数据结果普遍具有一次性的缺陷，而且变量难以控制 ；\newline
> 其次，通过问卷调查得到的数据，只能对测试人
员的行为进行静态分析，而人类的行为选择是动态变化
的[
26] \newline
> 最后，垃圾分类等资源环境问题是在受到人类各
种行为特征和行为选择的长期作用影响下形成的，一次
简单的问卷调查很难得到测试人员的真实行为信息。

## 实验设计机制与参数选择
使用的时z-tree
## 研究假设与实验设计
该实验设计了一个完全控制组和五个实验组：
1. 声誉控制组
2. 奖励实验组
3. 惩罚实验组
4. 奖励惩罚实验组
5. 社会规制实验组 \par
Ostrom[
28]，Rueden & Gurven
[29]
的研究表明有代价的惩罚对维持合作具有明显的作用，
人们宁愿付出代价惩罚搭便车。Gintis & Fehr[
30-31]比较
设置惩罚之前和之后的捐献，发现在设置惩罚之前，约
10 次后捐献降到一个较低的水平，并且上次比平均捐献
水平高的参与者，这次较少捐献。在设置惩罚之后，平
均捐献水平保持在个人拥有的一半货币（实验中使用的
捐赠代替物）以上，高捐献情境下，几乎没有人继续使
用惩罚。

## 实验结果与分析
## 个体特征与垃圾分类行为的联系
\footnote{文中，设置环境规制的时候，能够使垃圾分类率维持在规制水平左右，根据作者的结果来看，有一部分的参与者的垃圾分类率维持在一个较低的水平；然而，这是一个单次博弈，如果进行重复博弈，结果是否会有不同}


# REFERENCE
\noindent
[1] 基于行为经济学的环境政策有效性分析，刘金平 孔元
